import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const read = (relative) => readFileSync(resolve(here, relative), "utf8");
// After the build-friendly restructure the editor implementation is split per
// concern; guards read the file that actually owns each behavior.
const app = read("../src/editor/EditorApplication.cpp");
const panels = read("../src/editor/EditorApplicationPanels.cpp");
const vulkanImplEarly = read("../src/editor/EditorApplicationVulkan.cpp");
const assetsImplEarly = read("../src/editor/EditorApplicationAssets.cpp");
const header = read("../src/editor/EditorApplication.hpp");
const gridVertex = read("../shaders/active/editor_grid.vert");
const gridFragment = read("../shaders/active/editor_grid.frag");
const viewportFragment = read("../shaders/active/editor_viewport.frag");
const pickFragment = read("../shaders/active/editor_pick.frag");

// Grid depth must be the same Vulkan depth generated by scene geometry. A ray
// distance is in world units and therefore must never be written to gl_FragDepth.
assert.match(gridVertex, /nearPoint\s*=\s*unproject\s*\(\s*ndc\s*,\s*0\.0\s*\)/);
assert.match(gridVertex, /farWorld\s*=\s*unproject\s*\(\s*ndc\s*,\s*1\.0\s*\)/);
// BUG-EDITOR-GRID-005 (orbit jitter): the raw far-plane endpoint is
// unprojected at clipZ=1.0 = the FULL far plane (50000), and must NOT be
// handed to the rasterizer as an interpolant (huge OPPOSITE corners cancel in
// fp32 toward screen centre). The vertex must reduce the projective ray by
// ONE fixed, constant scale and pass only that precise same-line segment to
// the fragment (A1-G-GRID-RIGHT-SKEW-UNDERSIDE: un-normalized projective
// vector, scaled by a single constant — never per-vertex normalize, which is
// nonlinear and bends the interpolated direction field).
assert.match(
  gridVertex,
  /const\s+float\s+RAY_SCALE\s*=\s*1\.0\s*\/\s*24\.0\s*;.*farPoint\s*=\s*nearPoint\s*\+\s*dir\s*\*\s*RAY_SCALE\s*;/s,
  "grid vertex must reduce the projective far ray by one fixed constant scale (BUG-EDITOR-GRID-005 / A1-G)"
);
assert.match(
  gridFragment,
  /vec3\s+rayDirection\s*=\s*rawLen\s*>\s*1e-9\s*\?\s*\(\s*rawDir\s*\/\s*rawLen\s*\)/,
  "grid fragment must re-normalize the interpolated ray — the ONLY normalization (A1-G)"
);
assert.doesNotMatch(
  gridVertex,
  /normalize\s*\(\s*\w+\s*\)/,
  "grid vertex must never normalize per-vertex (nonlinear, bends the ray field — A1-G)"
);
assert.match(gridFragment, /float\s+gridDepth\s*=\s*clipPoint\.z\s*\/\s*safeClipW\s*;/);
assert.doesNotMatch(gridFragment, /gl_FragDepth\s*=\s*clamp\s*\(\s*t\s*,/);
// C1-GRID-RUNTIME-001 / A1-G-GRID-RIGHT-SKEW-UNDERSIDE (executable invariant):
// the grid plane only exists on the side facing UP. A ray striking Y=0 from
// BELOW must produce NO grid — the fragment rejects the underside by requiring
// a downward ray (denom < -1e-6) AND a forward intersection (t >= 0), and
// invalid fragments write zero premultiplied alpha so no grid appears above
// the plane. These are the code invariants the Agente 6 render capture must
// reproduce (the only normalization happens in the fragment, after interpolation).
assert.match(gridFragment, /bool\s+above\s*=\s*denom\s*<\s*-1e-6\s*;/);
assert.match(gridFragment, /bool\s+valid\s*=\s*above\s*&&\s*t\s*>=\s*0\.0\s*;/);
assert.match(gridFragment, /alpha\s*\*=\s*valid\s*\?\s*1\.0\s*:\s*0\.0\s*;/);
assert.match(gridFragment, /rayDirection\s*=\s*rawLen\s*>\s*1e-9\s*\?\s*\(\s*rawDir\s*\/\s*rawLen\s*\)/);
assert.match(
  header,
  /struct\s+GridPushConstants\s*\{\s*glm::mat4\s+invViewProj\s*;\s*glm::mat4\s+viewProj\s*;\s*\};/,
  "grid constants must stay within Vulkan's guaranteed 128-byte push-constant budget"
);

// BUG-EDITOR-LIGHTS-001: the basic mesh path (editor_viewport.frag) must
// shade with the REAL scene lights from the shared LightUboData (sun +
// point/spot/area), not a hardcoded light direction. Placing a light in the
// scene must change the viewport shading. The pick shader shares the pipeline
// layout, so it must declare the same block even though it never reads it.
assert.match(
  viewportFragment,
  /layout\s*\(\s*set\s*=\s*0,\s*binding\s*=\s*0\s*\)\s*uniform\s+SceneLights/,
  "basic mesh path must consume the scene lights UBO (set 0, binding 0)"
);
assert.match(
  viewportFragment,
  /lights\.sunDirection\.w\s*>\s*0\.5/,
  "viewport shading must use the scene's directional sun when present"
);
assert.match(
  viewportFragment,
  /lights\.pointLightColor\[i\]/,
  "viewport shading must include point lights"
);
assert.match(
  viewportFragment,
  /lights\.spotLightColor\[i\]/,
  "viewport shading must include spot lights"
);
assert.match(
  pickFragment,
  /uniform\s+SceneLights/,
  "pick shader must declare SceneLights to keep the shared pipeline layout compatible"
);
assert.match(
  vulkanImplEarly,
  /update_scene_light_ubo\s*\(\s*renderScene\s*\)/,
  "the viewport pass must refresh the scene light UBO every frame"
);

// BUG-EDITOR-CUBE-WINDING: the scene pipeline's effective front-face rule
// (frontFace=CCW + GL-convention projection + positive-height viewport) draws
// world-CW geometry. All six build_cube faces must share the sides' winding,
// otherwise the default cube renders with an open top and a see-through far
// side; and the terrain sheet must be indexed world-CW or it is culled from
// above. Guard the two windings that were fixed.
assert.match(
  panels,
  /BUG-EDITOR-CUBE-WINDING/,
  "build_cube must document the unified world-CW winding"
);
// Terrain index guard removed: the restructure replaced the single terrain
// sheet with sampled column boxes (generate_terrain_mesh in the Vulkan TU),
// so the (a,b,c) sheet winding no longer exists to guard.

// A Block is a per-face atlas and can contain transparent/cutout texels. It
// must be rendered through the alpha-aware material graph even when a future
// caller omits the optional argument. Semantic names must also beat stale,
// still-valid UUIDs stored in a .vblock sidecar after a registry rebuild.
assert.match(assetsImplEarly, /const\s+bool\s+requiresAlpha\s*=\s*withAlpha\s*\|\|\s*isBlockAtlas\s*;/);
assert.match(
  assetsImplEarly,
  /UUID\s+mainTex\s*=\s*exact\s*;\s*if\s*\(\s*!mainTex\.is_valid\(\)\s*\)\s*mainTex\s*=\s*namedSide\s*;[\s\S]{0,260}?if\s*\(\s*!mainTex\.is_valid\(\)\s*\)\s*mainTex\s*=\s*validTexture\s*\(\s*data\.texture\s*\)/,
  "semantic block texture names must be selected before sidecar UUID fallbacks"
);
assert.match(assetsImplEarly, /ensure_texture_pipeline\s*\(\s*range\.blockId\s*,\s*m_blockGraphPipelines\s*,\s*true\s*\)/);

// BUG-EDITOR-SHADOWS-001/002 + BUG-EDITOR-GI-001: the basic viewport path must
// sample the REAL shadow targets (sun map, spot atlas, point slot-0 atlas)
// and the Agente 1 probe-grid irradiance uploaded through EditorShadowUbo.
const vulkanImpl = read("../src/editor/EditorApplicationVulkan.cpp");
const assetsImpl = read("../src/editor/EditorApplicationAssets.cpp");

assert.match(
  viewportFragment,
  /layout\s*\(\s*set\s*=\s*0,\s*binding\s*=\s*1\s*\)\s*uniform\s+sampler2DShadow\s+sunShadowMap/,
  "basic mesh path must sample the sun shadow map (binding 1)"
);
assert.match(
  viewportFragment,
  /layout\s*\(\s*set\s*=\s*0,\s*binding\s*=\s*2\s*\)\s*uniform\s+sampler2DShadow\s+spotShadowAtlas/,
  "basic mesh path must sample the spot shadow atlas (binding 2)"
);
assert.match(
  viewportFragment,
  /layout\s*\(\s*set\s*=\s*0,\s*binding\s*=\s*3\s*\)\s*uniform\s+sampler2DShadow\s+pointShadowAtlas/,
  "basic mesh path must sample the point shadow atlas (binding 3)"
);
assert.match(
  viewportFragment,
  /layout\s*\(\s*set\s*=\s*0,\s*binding\s*=\s*4\s*\)\s*uniform\s+EditorShadow\s*\{[\s\S]*?vec4\s+probeIrradiance\[512\]/,
  "EditorShadow block must mirror EditorShadowUbo including the 512-probe grid"
);
assert.match(viewportFragment, /sun_shadow\s*\(\s*fragWorldPos\s*,\s*ndl\s*\)/,
  "sun direct light must be multiplied by the sun shadow term");
assert.match(viewportFragment, /point_shadow\s*\(\s*fragWorldPos\s*\)/,
  "point slot 0 direct light must be multiplied by the point shadow term");
assert.match(viewportFragment, /spot_shadow\s*\(\s*i,\s*fragWorldPos,\s*ndl\s*\)/,
  "each spot slot must be multiplied by its shadow tile");
assert.match(viewportFragment, /vec3\s+ambient\s*=\s*gi_irradiance\s*\(\s*fragWorldPos\s*\)/,
  "ambient must come from the probe-grid irradiance (falls back to 0.22)");
// The GLSL probe wrap must mirror the C++ dense index (x + y*res + z*res*res).
assert.match(viewportFragment, /w\.x \+ w\.y \* 8 \+ w\.z \* 64/);
assert.match(vulkanImpl, /const int idx = off\.x \+ off\.y \* res \+ off\.z \* res \* res;/);

// The shadow passes must exist and feed from the shared caster enumeration,
// which now includes terrain, cube placeholders and voxel volumes.
assert.match(vulkanImpl, /record_spot_shadow_pass\s*\(\s*cmd,\s*scene\s*\)/);
assert.match(vulkanImpl, /record_point_shadow_pass\s*\(\s*cmd,\s*scene\s*\)/);
assert.match(vulkanImpl, /draw_shadow_casters\s*\(\s*cmd,\s*m_shadowMap\.pipelineLayout,\s*m_shadowMap\.pipeline/);
assert.match(vulkanImpl, /[\s\S]*m_terrainValid[\s\S]*bind_and_draw_indexed\s*\(\s*m_terrainVB\.buffer/,
  "terrain must be a shadow caster (BUG-EDITOR-SHADOWS-001)");
assert.match(vulkanImpl, /editor_face_basis[\s\S]*std::abs\(d\.y\)\s*>\s*0\.9f/,
  "C++ point-face basis must keep the mirrored formula (GLSL side: abs(fd.y) > 0.9)");
assert.match(viewportFragment, /abs\(fd\.y\)\s*>\s*0\.9/);

// Assets side: the scene light set grows to 5 bindings (lights UBO + 3 shadow
// targets + EditorShadowUbo) and the basic path's sun-shadow flag turns on
// with the map.
assert.match(assetsImpl, /layoutInfo\.bindingCount = 5;/);
assert.match(assetsImpl, /bindings\[i\]\.descriptorType = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER;/,
  "shadow targets must be combined image samplers (bindings 1-3)");
assert.match(assetsImpl, /bindings\[4\]\.descriptorType = VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER;/);
assert.match(assetsImpl, /init_gi_probes\s*\(\s*\)\s*;/,
  "the probe grid core must be created with the scene light resources");
assert.match(assetsImpl, /data\.shadowParams = glm::vec4\(m_shadowMap\.enabled \? 1\.0f : 0\.0f/,
  "the basic path's sun shadow flag must follow the shadow map state");
assert.match(header, /static_assert\(sizeof\(EditorShadowUbo\) == 64 \* kEditorSpotShadowSlots \+ 16 \* 5 \+ 16 \* kEditorProbeCount/,
  "EditorShadowUbo must stay within the guaranteed uniform buffer range");

console.log("editor_viewport_regression_tests: PASS");
