import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const read = (relative) => readFileSync(resolve(here, relative), "utf8");
const app = read("../src/editor/EditorApplication.cpp");
const header = read("../src/editor/EditorApplication.hpp");
const gridVertex = read("../shaders/active/editor_grid.vert");
const gridFragment = read("../shaders/active/editor_grid.frag");
const viewportFragment = read("../shaders/active/editor_viewport.frag");
const pickFragment = read("../shaders/active/editor_pick.frag");

// Grid depth must be the same Vulkan depth generated by scene geometry. A ray
// distance is in world units and therefore must never be written to gl_FragDepth.
assert.match(gridVertex, /nearPoint\s*=\s*unproject\s*\(\s*ndc\s*,\s*0\.0\s*\)/);
assert.match(gridVertex, /farPoint\s*=\s*unproject\s*\(\s*ndc\s*,\s*1\.0\s*\)/);
assert.match(gridFragment, /float\s+gridDepth\s*=\s*clipPoint\.z\s*\/\s*safeClipW\s*;/);
assert.doesNotMatch(gridFragment, /gl_FragDepth\s*=\s*clamp\s*\(\s*t\s*,/);
assert.match(
  header,
  /struct\s+GridPushConstants\s*\{\s*glm::mat4\s+invViewProj\s*;\s*glm::mat4\s+viewProj\s*;\s*\};/,
  "grid constants must stay within Vulkan's guaranteed 128-byte push-constant budget"
);

// BUG-EDITOR-LIGHTS-001: the basic mesh path (editor_viewport.frag) must
// shade with the REAL scene lights from the shared LightUboData (sun +
// point/spot/area), not a hardcoded light direction. Placing a light in the
// scene must change the viewport shading. The pick shader shares the pipeline
// layout, so it must declare the same block even though it never reads it.
assert.match(
  viewportFragment,
  /layout\s*\(\s*set\s*=\s*0,\s*binding\s*=\s*0\s*\)\s*uniform\s+SceneLights/,
  "basic mesh path must consume the scene lights UBO (set 0, binding 0)"
);
assert.match(
  viewportFragment,
  /lights\.sunDirection\.w\s*>\s*0\.5/,
  "viewport shading must use the scene's directional sun when present"
);
assert.match(
  viewportFragment,
  /lights\.pointLightColor\[i\]/,
  "viewport shading must include point lights"
);
assert.match(
  viewportFragment,
  /lights\.spotLightColor\[i\]/,
  "viewport shading must include spot lights"
);
assert.match(
  pickFragment,
  /uniform\s+SceneLights/,
  "pick shader must declare SceneLights to keep the shared pipeline layout compatible"
);
assert.match(
  app,
  /update_scene_light_ubo\s*\(\s*renderScene\s*\)/,
  "the viewport pass must refresh the scene light UBO every frame"
);

// BUG-EDITOR-CUBE-WINDING: the scene pipeline's effective front-face rule
// (frontFace=CCW + GL-convention projection + positive-height viewport) draws
// world-CW geometry. All six build_cube faces must share the sides' winding,
// otherwise the default cube renders with an open top and a see-through far
// side; and the terrain sheet must be indexed world-CW or it is culled from
// above. Guard the two windings that were fixed.
assert.match(
  app,
  /BUG-EDITOR-CUBE-WINDING/,
  "build_cube must document the unified world-CW winding"
);
assert.doesNotMatch(
  app,
  /indices\.push_back\(a\);\s*indices\.push_back\(c\);\s*indices\.push_back\(b\);/,
  "terrain indices must not regress to the world-CCW (a,c,b) order (culled from above)"
);
assert.match(
  app,
  /indices\.push_back\(a\);\s*indices\.push_back\(b\);\s*indices\.push_back\(c\);/,
  "terrain indices must stay world-CW (a,b,c) so the sheet survives above views"
);

// A Block is a per-face atlas and can contain transparent/cutout texels. It
// must be rendered through the alpha-aware material graph even when a future
// caller omits the optional argument. Semantic names must also beat stale,
// still-valid UUIDs stored in a .vblock sidecar after a registry rebuild.
assert.match(app, /const\s+bool\s+requiresAlpha\s*=\s*withAlpha\s*\|\|\s*isBlockAtlas\s*;/);
assert.match(
  app,
  /UUID\s+mainTex\s*=\s*exact\s*;\s*if\s*\(\s*!mainTex\.is_valid\(\)\s*\)\s*mainTex\s*=\s*namedSide\s*;[\s\S]{0,260}?if\s*\(\s*!mainTex\.is_valid\(\)\s*\)\s*mainTex\s*=\s*validTexture\s*\(\s*data\.texture\s*\)/,
  "semantic block texture names must be selected before sidecar UUID fallbacks"
);
assert.match(app, /ensure_texture_pipeline\s*\(\s*range\.blockId\s*,\s*m_blockGraphPipelines\s*,\s*true\s*\)/);

console.log("editor_viewport_regression_tests: PASS");
