import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const read = (relative) => readFileSync(resolve(here, relative), "utf8");
// After the build-friendly restructure the editor implementation is split per
// concern; guards read the file that actually owns each behavior.
const app = read("../src/editor/EditorApplication.cpp");
const panels = read("../src/editor/EditorApplicationPanels.cpp");
const vulkanImplEarly = read("../src/editor/EditorApplicationVulkan.cpp");
const assetsImplEarly = read("../src/editor/EditorApplicationAssets.cpp");
const header = read("../src/editor/EditorApplication.hpp");
const gridVertex = read("../shaders/active/editor_grid.vert");
const gridFragment = read("../shaders/active/editor_grid.frag");
const viewportVertex = read("../shaders/active/editor_viewport.vert");
const materialVertex = read("../shaders/active/editor_material.vert");
const viewportFragment = read("../shaders/active/editor_viewport.frag");
const voxelFragment = read("../shaders/active/voxel.frag");
const pickFragment = read("../shaders/active/editor_pick.frag");
const materialPipelineImpl = read("../src/engine/rendering/vulkan/MaterialPipeline.cpp");
const gameAppImpl = read("../src/app/VulkanEngineApp.cpp");
const showcaseGameplayImpl = read("../src/app/ShowcaseGameplay.cpp");

// Grid depth must be the same Vulkan depth generated by scene geometry. A ray
// distance is in world units and therefore must never be written to gl_FragDepth.
assert.match(gridVertex, /nearPoint\s*=\s*unproject\s*\(\s*ndc\s*,\s*0\.0\s*\)/);
// VIS-GRID-001: avoid the 50 km far-plane endpoint. clipZ=0.5 lies on the same
// projective ray while keeping the interpolant camera-local and precise.
assert.match(
  gridVertex,
  /vec3\s+localPoint\s*=\s*unproject\s*\(\s*ndc\s*,\s*0\.5\s*\)\s*;\s*rayVector\s*=\s*localPoint\s*-\s*nearPoint\s*;/,
  "grid vertex must use the camera-local clipZ=0.5 projective ray (VIS-GRID-001)"
);
assert.match(
  gridFragment,
  /vec3\s+rayDirection\s*=\s*rawLen\s*>\s*1e-9\s*\?\s*\(\s*rawDir\s*\/\s*rawLen\s*\)/,
  "grid fragment must re-normalize the interpolated ray — the ONLY normalization (A1-G)"
);
assert.doesNotMatch(
  gridVertex,
  /normalize\s*\(\s*\w+\s*\)/,
  "grid vertex must never normalize per-vertex (nonlinear, bends the ray field — A1-G)"
);
assert.match(gridFragment, /float\s+gridDepth\s*=\s*clipPoint\.z\s*\/\s*safeClipW\s*;/);
assert.doesNotMatch(gridFragment, /gl_FragDepth\s*=\s*clamp\s*\(\s*t\s*,/);
// C1-GRID-RUNTIME-001 / A1-G-GRID-RIGHT-SKEW-UNDERSIDE (executable invariant):
// the grid plane only exists on the side facing UP. A ray striking Y=0 from
// BELOW must produce NO grid — the fragment rejects the underside by requiring
// a downward ray (denom < -1e-6) AND a forward intersection (t >= 0), and
// invalid fragments write zero premultiplied alpha so no grid appears above
// the plane. These are the code invariants the Agente 6 render capture must
// reproduce (the only normalization happens in the fragment, after interpolation).
assert.match(gridFragment, /bool\s+above\s*=\s*denom\s*<\s*-1e-6\s*;/);
assert.match(gridFragment, /bool\s+valid\s*=\s*above\s*&&\s*t\s*>=\s*0\.0\s*;/);
assert.match(gridFragment, /alpha\s*\*=\s*valid\s*\?\s*1\.0\s*:\s*0\.0\s*;/);
assert.match(gridFragment, /rayDirection\s*=\s*rawLen\s*>\s*1e-9\s*\?\s*\(\s*rawDir\s*\/\s*rawLen\s*\)/);
assert.match(
  header,
  /struct\s+GridPushConstants\s*\{\s*glm::mat4\s+invViewProj\s*;\s*glm::mat4\s+viewProj\s*;\s*\};/,
  "grid constants must stay within Vulkan's guaranteed 128-byte push-constant budget"
);

// BUG-EDITOR-LIGHTS-001: the basic mesh path (editor_viewport.frag) must
// shade with the REAL scene lights from the shared LightUboData (sun +
// point/spot/area), not a hardcoded light direction. Placing a light in the
// scene must change the viewport shading. The pick shader shares the pipeline
// layout, so it must declare the same block even though it never reads it.
assert.match(
  viewportFragment,
  /layout\s*\(\s*set\s*=\s*0,\s*binding\s*=\s*0\s*\)\s*uniform\s+SceneLights/,
  "basic mesh path must consume the scene lights UBO (set 0, binding 0)"
);
assert.match(
  viewportFragment,
  /lights\.sunDirection\.w\s*>\s*0\.5/,
  "viewport shading must use the scene's directional sun when present"
);
assert.match(
  viewportFragment,
  /lights\.pointLightColor\[i\]/,
  "viewport shading must include point lights"
);
assert.match(
  viewportFragment,
  /lights\.spotLightColor\[i\]/,
  "viewport shading must include spot lights"
);
assert.match(
  pickFragment,
  /uniform\s+SceneLights/,
  "pick shader must declare SceneLights to keep the shared pipeline layout compatible"
);
assert.match(
  vulkanImplEarly,
  /update_scene_light_ubo\s*\(\s*renderScene\s*\)/,
  "the viewport pass must refresh the scene light UBO every frame"
);
assert.match(
  viewportVertex,
  /transpose\s*\(\s*inverse\s*\(\s*mat3\s*\(\s*push\.model\s*\)\s*\)\s*\)\s*\*\s*inNormal/,
  "basic viewport normals must be transformed to world space with inverse-transpose"
);
assert.match(
  materialVertex,
  /transpose\s*\(\s*inverse\s*\(\s*mat3\s*\(\s*push\.model\s*\)\s*\)\s*\)\s*\*\s*inNormal/,
  "material-graph normals must remain correct under non-uniform entity scale"
);
assert.match(
  viewportFragment,
  /viewDir\s*=\s*normalize\s*\(\s*lights\.cameraPosition\.xyz\s*-\s*fragWorldPos\s*\)/,
  "rim lighting must be relative to the real editor camera, not world origin"
);
assert.match(
  viewportFragment,
  /float\s+dist\s*=\s*length\s*\(\s*fragWorldPos\s*-\s*lights\.cameraPosition\.xyz\s*\)/,
  "viewport fog must use camera-to-fragment distance, not distance from world origin"
);

// BUG-EDITOR-CUBE-WINDING: the scene pipeline's effective front-face rule
// (frontFace=CCW + GL-convention projection + positive-height viewport) draws
// world-CW geometry. All six build_cube faces must share the sides' winding,
// otherwise the default cube renders with an open top and a see-through far
// side; and the terrain sheet must be indexed world-CW or it is culled from
// above. Guard the two windings that were fixed.
assert.match(
  panels,
  /BUG-EDITOR-CUBE-WINDING/,
  "build_cube must document the unified world-CW winding"
);
// Terrain index guard removed: the restructure replaced the single terrain
// sheet with sampled column boxes (generate_terrain_mesh in the Vulkan TU),
// so the (a,b,c) sheet winding no longer exists to guard.

// A Block is a per-face atlas and can contain transparent/cutout texels. It
// must be rendered through the alpha-aware material graph even when a future
// caller omits the optional argument. Semantic names must also beat stale,
// still-valid UUIDs stored in a .vblock sidecar after a registry rebuild.
assert.match(assetsImplEarly, /const\s+bool\s+requiresAlpha\s*=\s*withAlpha\s*\|\|\s*isBlockAtlas\s*;/);
assert.match(
  assetsImplEarly,
  /UUID\s+mainTex\s*=\s*exact\s*;\s*if\s*\(\s*!mainTex\.is_valid\(\)\s*\)\s*mainTex\s*=\s*namedSide\s*;[\s\S]{0,260}?if\s*\(\s*!mainTex\.is_valid\(\)\s*\)\s*mainTex\s*=\s*validTexture\s*\(\s*data\.texture\s*\)/,
  "semantic block texture names must be selected before sidecar UUID fallbacks"
);
assert.match(assetsImplEarly, /ensure_texture_pipeline\s*\(\s*range\.blockId\s*,\s*m_blockGraphPipelines\s*,\s*true\s*\)/);

// BUG-EDITOR-SHADOWS-001/002 + BUG-EDITOR-GI-001: the basic viewport path must
// sample the REAL shadow targets (sun map, spot atlas, point slot-0 atlas)
// and canonical DDGI irradiance uploaded through EditorShadowUbo.
const vulkanImpl = read("../src/editor/EditorApplicationVulkan.cpp");
const assetsImpl = read("../src/editor/EditorApplicationAssets.cpp");

assert.match(
  viewportFragment,
  /layout\s*\(\s*set\s*=\s*0,\s*binding\s*=\s*1\s*\)\s*uniform\s+sampler2DShadow\s+sunShadowMap/,
  "basic mesh path must sample the sun shadow map (binding 1)"
);
assert.match(
  viewportFragment,
  /layout\s*\(\s*set\s*=\s*0,\s*binding\s*=\s*2\s*\)\s*uniform\s+sampler2DShadow\s+spotShadowAtlas/,
  "basic mesh path must sample the spot shadow atlas (binding 2)"
);
assert.match(
  viewportFragment,
  /layout\s*\(\s*set\s*=\s*0,\s*binding\s*=\s*3\s*\)\s*uniform\s+sampler2DShadow\s+pointShadowAtlas/,
  "basic mesh path must sample the point shadow atlas (binding 3)"
);
assert.match(
  viewportFragment,
  /layout\s*\(\s*set\s*=\s*0,\s*binding\s*=\s*4\s*\)\s*uniform\s+EditorShadow\s*\{[\s\S]*?vec4\s+probeIrradiance\[512\]/,
  "EditorShadow block must mirror EditorShadowUbo including the 512-probe grid"
);
assert.match(viewportFragment, /sun_shadow\s*\(\s*fragWorldPos\s*,\s*ndl\s*\)/,
  "sun direct light must be multiplied by the sun shadow term");
assert.match(viewportFragment, /float\s+sample_sun_cascade\s*\(/,
  "viewport sun shadows must sample cascades through the stable PCF helper");
assert.match(viewportFragment, /smoothstep\s*\(\s*split\s*-\s*blendWidth\s*,\s*split\s*,\s*viewDepth\s*\)/,
  "viewport must cross-fade cascade boundaries instead of hard-popping between maps");
assert.match(viewportFragment, /point_shadow\s*\(\s*fragWorldPos\s*,\s*ndl\s*\)/,
  "the selected point-light slot must be multiplied by the point shadow term");
assert.match(viewportFragment, /int\s+shadowPointIndex\s*=\s*int\(shadow\.pointParams\.w\s*\+\s*0\.5\)/,
  "point shadow atlas ownership must carry the matching LightUbo point slot");
assert.match(viewportFragment, /shadow\.pointViewProj\[face\]\s*\*\s*vec4\(worldPos,\s*1\.0\)/,
  "point shadow sampling must use the exact face VP uploaded by the renderer");
assert.match(viewportFragment, /spot_shadow\s*\(\s*i,\s*fragWorldPos,\s*ndl\s*\)/,
  "each spot slot must be multiplied by its shadow tile");
assert.match(viewportFragment, /vec3\s+ambient\s*=\s*gi_irradiance\s*\(\s*fragWorldPos\s*\)/,
  "ambient must come from the probe-grid irradiance (falls back to 0.22)");
// The GLSL probe wrap must mirror the C++ dense index (x + y*res + z*res*res).
assert.match(viewportFragment, /w\.x \+ w\.y \* 8 \+ w\.z \* 64/);
assert.match(vulkanImpl, /const int idx = off\.x \+ off\.y \* res \+ off\.z \* res \* res;/);

// The shadow passes must exist and feed from the shared caster enumeration,
// which now includes terrain, cube placeholders and voxel volumes.
assert.match(vulkanImpl, /record_spot_shadow_pass\s*\(\s*cmd,\s*scene\s*\)/);
assert.match(vulkanImpl, /record_point_shadow_pass\s*\(\s*cmd,\s*scene\s*\)/);
assert.doesNotMatch(
  vulkanImpl,
  /if\s*\(\s*!hasSun\s*\)\s*return\s*;/,
  "point/spot shadow passes must still run when the scene has no directional sun"
);
assert.match(
  vulkanImpl,
  /sunCastsShadows\s*=\s*light\.castShadows/,
  "directional Cast Shadows must gate the sun depth pass"
);
assert.match(
  assetsImpl,
  /if\s*\(\s*!hasDirectionalSun\s*&&\s*!hasAnyAuthoredLight\s*\)/,
  "procedural fallback sun must not mask authored point/spot/area lights"
);
assert.match(
  panels,
  /\(l\.type == LightType::Spot \|\| l\.type == LightType::Area\)[\s\S]{0,500}?rotation\.x\s*=\s*-90\.0f/,
  "converting an untouched point/directional light to Spot/Area must initialize a usable downward orientation"
);
assert.match(vulkanImpl, /draw_shadow_casters\s*\(\s*cmd,\s*m_shadowMap\.pipelineLayout,\s*m_shadowMap\.pipeline/);
assert.match(vulkanImpl, /[\s\S]*m_terrainValid[\s\S]*bind_and_draw_indexed\s*\(\s*m_terrainVB\.buffer/,
  "terrain must be a shadow caster (BUG-EDITOR-SHADOWS-001)");
assert.match(vulkanImpl, /editor_face_basis[\s\S]*std::abs\(d\.y\)\s*>\s*0\.9f/,
  "C++ point-face basis must preserve the vertical-face up-vector convention");
assert.match(vulkanImpl, /return\s+glm::lookAt\(position,\s*position\s*\+\s*d,\s*u\)/,
  "point face views must use a correct column-major lookAt basis");
assert.match(vulkanImpl, /if\s*\(!out\.point0\.enabled\s*&&\s*light\.castShadows\)/,
  "a non-shadowing earlier point light must not consume the sole point-shadow atlas");
assert.match(vulkanImpl, /out\.point0\.lightIndex\s*=\s*pointSlot/,
  "the selected point shadow caster must remember its LightUbo slot");
assert.doesNotMatch(vulkanImpl, /outWorldPos\s*=\s*world\.xyz/,
  "point shadow depth must never treat clip-space position as world-space position");

// Assets side: the scene light set grows to 5 bindings (lights UBO + 3 shadow
// targets + EditorShadowUbo) and the basic path's sun-shadow flag turns on
// with the map.
assert.match(assetsImpl, /layoutInfo\.bindingCount = 5;/);
assert.match(assetsImpl, /bindings\[i\]\.descriptorType = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER;/,
  "shadow targets must be combined image samplers (bindings 1-3)");
assert.match(assetsImpl, /bindings\[4\]\.descriptorType = VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER;/);
assert.match(assetsImpl, /init_gi_probes\s*\(\s*\)\s*;/,
  "the canonical DDGI provider must be created with the scene light resources");
assert.match(vulkanImpl,
  /create_global_illumination_provider\s*\([\s\S]{0,180}?GiBackend::Ddgi/,
  "the editor viewport must instantiate the public canonical DDGI provider");
assert.match(vulkanImpl,
  /core\.update\s*\(\s*m_editorCamera\.position/,
  "the editor frame must update canonical DDGI from the real editor camera");
assert.match(vulkanImpl, /m_shadowUboData\.probeIrradiance\[idx\]\s*=\s*probe\.radianceVisibility/,
  "canonical DDGI probe output must feed the UBO consumed by the viewport shader");
assert.match(vulkanImpl,
  /const\s+glm::vec3\s+lightDir\s*=\s*glm::normalize\(direction\)/,
  "spot shadow camera must point in the same light->surface direction used by the lighting cone");
assert.match(vulkanImpl,
  /glm::perspective\(2\.0f\s*\*\s*outer,\s*1\.0f/,
  "spot shadow FOV must follow the authored outer half-angle instead of a fixed 90 degrees");
assert.match(vulkanImpl,
  /radius\s*=\s*std::ceil\(radius\s*\*\s*16\.0f\)\s*\/\s*16\.0f/,
  "sun cascades must use a quantized rotation-stable extent to prevent edge shimmer");
assert.match(vulkanImpl,
  /rounded\s*=\s*glm::round\(glm::vec2\(origin\)\)/,
  "sun cascade projection must snap to the shadow texel grid");
assert.match(vulkanImpl,
  /casterPad\s*=\s*std::max\(16\.0f,\s*radius\s*\*\s*1\.5f\)/,
  "sun cascade depth must include off-frustum casters near the camera");
assert.match(vulkanImpl,
  /const float lambda = 0\.85f/,
  "sun cascades must concentrate more resolution near the camera");
assert.match(vulkanImpl,
  /radius\s*=\s*std::sqrt\(halfDepth\s*\*\s*halfDepth\s*\+\s*wf\s*\*\s*wf\s*\+\s*hf\s*\*\s*hf\)/,
  "sun cascade radius must be analytic and independent of camera orientation");
assert.match(vulkanImpl,
  /ortFar\s*=\s*std::max\(ortNear\s*\+\s*1\.0f,\s*2\.0f\s*\*\s*\(radius\s*\+\s*casterPad\)\)/,
  "sun cascade depth extent must be rotation-stable as well as XY-stable");
assert.match(vulkanImpl,
  /rasterizer\.depthBiasEnable\s*=\s*VK_TRUE;[\s\S]{0,220}?depthBiasSlopeFactor\s*=\s*1\.75f/,
  "directional/spot shadow rasterization must use slope-scaled depth bias to prevent self-shadow acne");
assert.match(viewportFragment,
  /lights\.sunCascadeVP\[c\]\s*\*\s*vec4\(worldPos,\s*1\.0\)/,
  "basic viewport sun shadows must sample the selected cascade instead of cascade 0 only");
assert.match(viewportFragment,
  /tap\s*=\s*clamp\(tap,\s*tileMin\s*\+\s*vec2\(texel\),\s*tileMax\s*-\s*vec2\(texel\)\)/,
  "sun PCF taps must stay inside the selected atlas tile");
assert.match(materialPipelineImpl,
  /return lit \/ 9\.0/,
  "material-graph sun shadows must use filtered 3x3 comparison instead of a single unstable tap");
assert.match(assetsImpl,
  /data\.areaLightHalf\[areaCount\]\s*=\s*glm::vec4\([\s\S]{0,120}?std::max\(light\.range,\s*0\.01f\)/,
  "area-light attenuation range must reach the shared light UBO"
);
assert.match(assetsImpl, /if\s*\(!hasDirectionalSun\)\s*\{\s*data\.sunDirection/,
  "the light UBO must keep the same first directional sun used by shadows/GI");
assert.match(assetsImpl, /else if\s*\(light\.type\s*==\s*LightType::Spot\)\s*\{[\s\S]{0,500}?if\s*\(spotCount\s*<\s*Rendering::kMaxSpotLights\)/,
  "spot overflow must be dropped as spot overflow, never reinterpreted as a point light");
assert.match(assetsImpl, /data\.shadowParams = glm::vec4\(m_shadowMap\.enabled \? 1\.0f : 0\.0f/,
  "the basic path's sun shadow flag must follow the shadow map state");
assert.equal(
  (assetsImpl.match(/data\.cameraForward\s*=\s*glm::vec4\(glm::normalize\(m_editorCamera\.get_front\(\)\),\s*0\.0f\);/g) ?? []).length,
  2,
  "both viewport and material LightUboData writers must use the canonical world-space editor camera forward vector"
);
assert.doesNotMatch(
  assetsImpl,
  /-view\[2\]\[0\][\s\S]{0,80}-view\[2\]\[1\][\s\S]{0,80}-view\[2\]\[2\]/,
  "cascade selection must never reconstruct cameraForward from convention-sensitive glm::lookAt matrix indexing"
);
assert.match(header, /static_assert\(sizeof\(EditorShadowUbo\) == 64 \* \(kEditorSpotShadowSlots \+ 6\) \+ 16 \* 5 \+ 16 \* kEditorProbeCount/,
  "EditorShadowUbo must stay within the guaranteed uniform buffer range");

// EDITOR-MATERIAL-LOCAL-SHADOW-014/015: blocks, skins and arbitrary material
// graphs must consume the SAME spot/point shadow atlases as the basic viewport,
// and their cached descriptor sets must be refreshed after shadow recreation.
assert.match(materialPipelineImpl, /uniform\s+sampler2DShadow\s+shadowMap/,
  "generated material sun shadows must use the compare-enabled sampler as sampler2DShadow");
assert.match(materialPipelineImpl, /sampleSunCascade\s*\(\s*c\s*,\s*worldPos\s*,\s*bias\s*\)/,
  "generated material sun shadows must use the same cascade PCF helper");
assert.match(materialPipelineImpl, /smoothstep\(split - blendWidth, split, viewDepth\)/,
  "generated material shadows must cross-fade cascade boundaries");
assert.match(materialPipelineImpl, /computeShadow\(vWorldPos, ndl\)/,
  "generated materials must feed surface angle into the sun shadow bias");
assert.match(materialPipelineImpl, /uniform\s+sampler2DShadow\s+spotShadowAtlas/,
  "generated material shaders must declare the editor spot shadow atlas");
assert.match(materialPipelineImpl, /uniform\s+sampler2DShadow\s+pointShadowAtlas/,
  "generated material shaders must declare the editor point shadow atlas");
assert.match(materialPipelineImpl, /computeSpotShadow\s*\(\s*int\s+i,\s*vec3\s+worldPos,\s*float\s+ndl\s*\)/,
  "generated material shaders must evaluate spot shadows");
assert.match(materialPipelineImpl, /computePointShadow\s*\(\s*vec3\s+worldPos,\s*float\s+ndl\s*\)/,
  "generated material shaders must evaluate the selected point shadow owner");
assert.match(assetsImpl, /out\.spotShadowSamplerBinding\s*=\s*gen\.spotShadowSamplerBinding/);
assert.match(assetsImpl, /out\.pointShadowSamplerBinding\s*=\s*gen\.pointShadowSamplerBinding/);
assert.match(assetsImpl, /data\.spotShadowVP\[i\]\s*=\s*m_shadowUboData\.spotViewProj\[i\]/,
  "material LightUboData must receive the same spot shadow matrices as the basic path");
assert.match(assetsImpl, /data\.pointShadowVP\[face\]\s*=\s*m_shadowUboData\.pointViewProj\[face\]/,
  "material LightUboData must receive the same point-face matrices as the basic path");
assert.match(assetsImpl, /for\s*\(auto&\s*\[id,\s*p\]\s*:\s*m_blockGraphPipelines\)[\s\S]{0,100}?refreshGraphSet\(p\)/,
  "block material descriptors must be refreshed when shadow images are recreated");
assert.match(assetsImpl, /writes\[i\]\.sType\s*=\s*VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET/,
  "shadow descriptor refresh writes must initialize VkWriteDescriptorSet::sType");

// GAME-AUTHORED-LIGHTS-016 / GAME-SPOT-CONE-017: the shipped canonical game
// renderer must consume authored showcase lights instead of merely exposing
// them as scene/title observables. The canonical flat light asset produced by
// the authoring tool is accepted, existing scene transforms are preserved, and
// the voxel spot cone keeps cos(inner) > cos(outer).
assert.match(showcaseGameplayImpl, /else if\s*\(root\.field\("type"\)\s*!=\s*nullptr\)/,
  "canonical flat showcase light documents must be consumed by the game");
assert.match(showcaseGameplayImpl, /transformComponents\.try_emplace\(/,
  "loading a light config must preserve an existing authored scene transform");
assert.match(gameAppImpl, /if\s*\(showcaseLightsAssetLoaded\)[\s\S]{0,900}?showcaseScene\.lightComponents/,
  "canonical sun state must be overridden from authored showcase LightComponents");
assert.match(gameAppImpl, /showcaseScene\.lightComponents[\s\S]{0,1600}?pushData\.spotLightPos/,
  "canonical local-light push constants must consume authored showcase LightComponents");
assert.match(voxelFragment, /float\s+cosOuter\s*=\s*min\([\s\S]{0,100}?cosInner\s*-\s*0\.001\)/,
  "voxel spot cone must preserve cos(inner) > cos(outer)");
assert.doesNotMatch(voxelFragment, /cosOuter\s*=\s*max\([^;]*cosInner\s*\+\s*0\.001/,
  "voxel spot cone must not invert inner/outer cosine ordering");

console.log("editor_viewport_regression_tests: PASS");
