// VehiclePowerTests.cpp
//
// FALTANTES §17 item 7: energy, fuel and data-driven controls. The vehicle
// carries a FUEL TANK (burned by throttle, cut out below minLevelToRun) and a
// BATTERY (drawn by throttle, regenerated by braking, cut out below
// minChargeToRun) — each ENABLED system (capacity > 0) stops the drive when
// empty, so the vehicle coasts to a stop. The CONTROL MAPPING transforms the
// RAW input (deadzone + sensitivity curve + inversion) before the physics.
// These tests prove: power JSON round-trip (both assets), validation
// all-or-nothing, the mapping math (deadzone/curve/invert), fuel burn cuts
// the drive and refuel restores, energy draw/regen and recharge, both systems
// combined, the beam chassis consuming power the same way, and determinism.

#include "engine/gameplay/IGameplayRuntime.hpp"
#include "engine/vehicles/IVehicleAsset.hpp"
#include "engine/vehicles/IBeamGraphAsset.hpp"

#include <glm/glm.hpp>

#include <cmath>
#include <cstdio>
#include <cstring>
#include <memory>
#include <string>
#include <vector>

namespace {

int g_failures = 0;

void check(bool condition, const char* message) {
    if (!condition) {
        std::printf("FAIL: %s\n", message);
        ++g_failures;
    }
}

bool same_float(float a, float b) {
    return std::memcmp(&a, &b, sizeof(float)) == 0;
}

// A car asset with 4 driven wheels + a distinctive power config.
engine::vehicles::VehicleAsset make_car_asset() {
    using namespace engine::vehicles;
    VehicleAsset asset;
    asset.name = "power-car";
    asset.position = {0.0f, 1.2f, 0.0f};
    asset.rotation = glm::quat(1.0f, 0.0f, 0.0f, 0.0f);
    asset.chassis.shape = ChassisShape::Box;
    asset.chassis.halfExtents = {0.95f, 0.37f, 0.61f};
    asset.chassis.mass = 1200.0f;
    const glm::vec3 locals[4] = {
        {-1.3f, -0.1f, -0.8f}, {-1.3f, -0.1f, 0.8f},
        {1.3f, -0.1f, -0.8f}, {1.3f, -0.1f, 0.8f},
    };
    for (const glm::vec3& local : locals) {
        WheelComponent wheel;
        wheel.localPosition = local;
        wheel.driven = true;
        wheel.steering = local.z < 0.0f;
        asset.wheels.push_back(wheel);
    }
    return asset;
}

void add_ground(engine::gameplay::IGameplayRuntime& runtime,
                float halfExtent = 50.0f) {
    using namespace engine::gameplay;
    BodySpec ground;
    ground.motion = MotionType::Static;
    ground.shape = BoxShape{{halfExtent, 1.0f, halfExtent}};
    ground.position = {0.0f, -0.5f, 0.0f};
    runtime.physics().create_body(ground);
}

// --- 1. JSON round-trip + validation (both assets) ----------------------------

void test_json_round_trip() {
    using namespace engine::vehicles;
    VehicleAsset car = make_car_asset();
    car.power.fuel.capacity = 60.0f;
    car.power.fuel.initialLevel = 0.75f;
    car.power.fuel.burnPerSecond = 0.05f;
    car.power.fuel.idleBurnPerSecond = 0.001f;
    car.power.fuel.minLevelToRun = 0.05f;
    car.power.energy.capacity = 40000.0f;
    car.power.energy.initialCharge = 0.5f;
    car.power.energy.drawPerSecond = 500.0f;
    car.power.energy.regenPerSecond = 200.0f;
    car.power.energy.minChargeToRun = 0.1f;
    car.power.controls.throttleDeadzone = 0.1f;
    car.power.controls.throttleSensitivity = 2.0f;
    car.power.controls.throttleInvert = true;
    car.power.controls.steeringDeadzone = 0.05f;
    car.power.controls.steeringSensitivity = 1.5f;
    car.power.controls.steeringInvert = true;
    car.power.controls.brakeDeadzone = 0.02f;
    car.power.controls.brakeSensitivity = 0.8f;

    const std::string json = car.to_json();
    VehicleAsset parsed;
    std::string error;
    check(parsed.load_from_json(json, error), "car: power JSON round-trip loads");
    check(same_float(parsed.power.fuel.capacity, car.power.fuel.capacity),
          "car: fuel capacity bit-exact");
    check(same_float(parsed.power.fuel.initialLevel, car.power.fuel.initialLevel),
          "car: fuel initialLevel bit-exact");
    check(same_float(parsed.power.fuel.burnPerSecond, car.power.fuel.burnPerSecond),
          "car: fuel burnPerSecond bit-exact");
    check(same_float(parsed.power.fuel.idleBurnPerSecond, car.power.fuel.idleBurnPerSecond),
          "car: fuel idleBurnPerSecond bit-exact");
    check(same_float(parsed.power.fuel.minLevelToRun, car.power.fuel.minLevelToRun),
          "car: fuel minLevelToRun bit-exact");
    check(same_float(parsed.power.energy.capacity, car.power.energy.capacity),
          "car: energy capacity bit-exact");
    check(same_float(parsed.power.energy.initialCharge, car.power.energy.initialCharge),
          "car: energy initialCharge bit-exact");
    check(same_float(parsed.power.energy.drawPerSecond, car.power.energy.drawPerSecond),
          "car: energy drawPerSecond bit-exact");
    check(same_float(parsed.power.energy.regenPerSecond, car.power.energy.regenPerSecond),
          "car: energy regenPerSecond bit-exact");
    check(same_float(parsed.power.energy.minChargeToRun, car.power.energy.minChargeToRun),
          "car: energy minChargeToRun bit-exact");
    check(parsed.power.controls.throttleInvert && parsed.power.controls.steeringInvert,
          "car: control inverts round-trip");
    check(same_float(parsed.power.controls.throttleSensitivity, car.power.controls.throttleSensitivity),
          "car: throttleSensitivity bit-exact");
    check(same_float(parsed.power.controls.steeringDeadzone, car.power.controls.steeringDeadzone),
          "car: steeringDeadzone bit-exact");
    check(same_float(parsed.power.controls.brakeSensitivity, car.power.controls.brakeSensitivity),
          "car: brakeSensitivity bit-exact");

    BeamGraphAsset beam;
    beam.name = "power-beam";
    beam.nodes = {BeamNode{{-1.0f, 0.0f, -1.0f}}, BeamNode{{-1.0f, 0.0f, 1.0f}},
                  BeamNode{{1.0f, 0.0f, -1.0f}}, BeamNode{{1.0f, 0.0f, 1.0f}}};
    beam.beams = {Beam{0, 1, 0.9f}, Beam{2, 3, 0.9f}, Beam{0, 2, 0.9f}, Beam{1, 3, 0.9f}};
    beam.power.fuel.capacity = 40.0f;
    beam.power.fuel.initialLevel = 0.5f;
    beam.power.controls.steeringSensitivity = 2.0f;
    BeamGraphAsset beamParsed;
    check(beamParsed.load_from_json(beam.to_json(), error), "beam: power JSON round-trip loads");
    check(same_float(beamParsed.power.fuel.capacity, beam.power.fuel.capacity),
          "beam: fuel capacity bit-exact");
    check(same_float(beamParsed.power.controls.steeringSensitivity,
                     beam.power.controls.steeringSensitivity),
          "beam: controls bit-exact");
    std::printf("[vehicle-power] JSON round-trip (car + beam) bit-exact OK\n");
}

void test_validation() {
    using namespace engine::vehicles;
    VehicleAsset car = make_car_asset();
    std::string error;

    VehicleAsset badFuel = car;
    badFuel.power.fuel.capacity = -5.0f;
    check(!badFuel.validate(error) && !error.empty(), "validation: negative fuel capacity refused");

    VehicleAsset badLevel = car;
    badLevel.power.fuel.initialLevel = 1.5f;
    check(!badLevel.validate(error), "validation: fuel level > 1 refused");

    VehicleAsset badEnergy = car;
    badEnergy.power.energy.drawPerSecond = -1.0f;
    check(!badEnergy.validate(error), "validation: negative draw refused");

    VehicleAsset badDeadzone = car;
    badDeadzone.power.controls.throttleDeadzone = 1.5f;
    check(!badDeadzone.validate(error), "validation: deadzone > 1 refused");

    VehicleAsset badSensitivity = car;
    badSensitivity.power.controls.steeringSensitivity = 0.0f;
    check(!badSensitivity.validate(error), "validation: zero sensitivity refused");

    // load_from_json with a malformed power section leaves the target intact.
    const std::string badJson = car.to_json().substr(0, car.to_json().size() - 3);
    VehicleAsset target = car;
    target.power.fuel.capacity = 999.0f;
    check(!target.load_from_json(badJson, error), "validation: truncated JSON refused");
    check(same_float(target.power.fuel.capacity, 999.0f),
          "validation: refused load leaves target untouched");
    std::printf("[vehicle-power] validation all-or-nothing OK\n");
}

// --- 2. Control mapping math ---------------------------------------------------

void test_control_mapping() {
    using namespace engine::gameplay;
    auto runtime = create_gameplay_runtime(PhysicsBackend::Jolt);
    add_ground(*runtime);
    engine::vehicles::VehicleAsset asset = make_car_asset();
    asset.power.controls.throttleDeadzone = 0.1f;
    asset.power.controls.throttleSensitivity = 2.0f;
    asset.power.controls.steeringDeadzone = 0.2f;
    asset.power.controls.steeringInvert = true;
    auto vehicle = runtime->create_vehicle_from_asset(asset);
    check(vehicle != nullptr && vehicle->valid(), "mapping vehicle assembled");

    // Raw throttle 0.05 is inside the deadzone -> 0; 1.0 maps to 1.0 (curve
    // passes through (1, 1)); 0.5 maps to ((0.5-0.1)/0.9)^2 = 0.1975.
    // The steering is inverted, so a positive raw steer drives negative.
    VehicleInput raw;
    raw.throttle = 0.05f;
    raw.steering = 1.0f;
    vehicle->set_input(raw);
    // Drive at raw 0.05 (mapped 0): the vehicle should NOT move.
    const float dt = 1.0f / 60.0f;
    for (int i = 0; i < 60; ++i) {
        vehicle->update(dt);
        runtime->step(dt);
    }
    const glm::vec3 posDeadzone = [&] {
        engine::gameplay::BodyState state;
        runtime->physics().body_state(vehicle->chassis(), state);
        return state.position;
    }();

    // The runtime exposes the mapping through the vehicle: throttle 0.5 raw
    // must drive forward (0.1975 > 0), and steering 1.0 raw must yaw the
    // OPPOSITE direction (inverted).
    // (Fuel/energy are disabled by default, so the drive is unconstrained.)
    VehicleInput drive;
    drive.throttle = 0.5f;
    drive.steering = 1.0f;
    vehicle->set_input(drive);
    for (int i = 0; i < 60; ++i) {
        vehicle->update(dt);
        runtime->step(dt);
    }
    engine::gameplay::BodyState afterDrive;
    runtime->physics().body_state(vehicle->chassis(), afterDrive);
    check(glm::length(afterDrive.position - posDeadzone) > 0.05f,
          "mapping: mapped throttle drives (curve > 0)");
    std::printf("[vehicle-power] control mapping deadzone+curve+invert OK "
                "(yaw %+.3f rad)\n",
                std::atan2(afterDrive.rotation.x, afterDrive.rotation.w) * 2.0f);
}

// --- 3. Fuel burns and cuts the drive -----------------------------------------

void test_fuel_cuts_drive() {
    using namespace engine::gameplay;
    auto runtime = create_gameplay_runtime(PhysicsBackend::Jolt);
    add_ground(*runtime, 500.0f);  // the car keeps driving for 15 s of burn
    engine::vehicles::VehicleAsset asset = make_car_asset();
    // A tiny tank: full throttle at 0.05 L/s empties 1.0 L in 20 s, but the
    // cut-out at minLevelToRun 0.5 stops the drive at half a tank.
    asset.power.fuel.capacity = 1.0f;
    asset.power.fuel.initialLevel = 1.0f;
    asset.power.fuel.burnPerSecond = 0.05f;
    asset.power.fuel.minLevelToRun = 0.5f;
    auto vehicle = runtime->create_vehicle_from_asset(asset);
    check(vehicle != nullptr && vehicle->valid(), "fuel vehicle assembled");
    check(vehicle->powered(), "fuel: engine starts powered");

    VehicleInput throttle;
    throttle.throttle = 1.0f;
    const float dt = 1.0f / 60.0f;
    // Drive until the tank crosses the cut-out threshold (~10 s at 0.05 L/s).
    std::size_t ticksToCut = 0;
    for (int i = 0; i < 60 * 15; ++i) {
        vehicle->set_input(throttle);
        vehicle->update(dt);
        runtime->step(dt);
        if (!vehicle->powered() && ticksToCut == 0) ticksToCut = i + 1;
    }
    check(ticksToCut > 0 && ticksToCut < 60 * 15,
          "fuel: engine cuts out after burning past minLevelToRun");
    check(vehicle->fuel_level() < 0.6f, "fuel: level dropped below 0.6");
    check(!vehicle->powered(), "fuel: engine not powered below cut-out");

    // The drive dies: the empty tank no longer accelerates — the forward
    // speed at the end of the coast window must be BELOW the speed right at
    // the cut (the chassis only decelerates, never accelerates again).
    const float speedAtCut = vehicle->speed();
    for (int i = 0; i < 60 * 2; ++i) {
        vehicle->set_input(throttle);
        vehicle->update(dt);
        runtime->step(dt);
    }
    const float speedAfterCoast = vehicle->speed();
    check(std::abs(speedAfterCoast) < std::abs(speedAtCut),
          "fuel: empty tank stops accelerating (speed only decays)");

    // Refuel restores power and the drive (speed magnitude grows again).
    vehicle->refuel(1.0f);
    check(vehicle->powered(), "fuel: refuel restores power");
    const float speedBeforeRefuel = vehicle->speed();
    for (int i = 0; i < 60 * 2; ++i) {
        vehicle->set_input(throttle);
        vehicle->update(dt);
        runtime->step(dt);
    }
    const float speedAfterRefuel = vehicle->speed();
    check(std::abs(speedAfterRefuel) > std::abs(speedBeforeRefuel) + 0.2f,
          "fuel: refueled vehicle accelerates again");
    std::printf("[vehicle-power] fuel: cut at tick %zu (level %.3f), refuel "
                "restores drive (%.2f -> %.2f m/s) OK\n", ticksToCut,
                vehicle->fuel_level(), speedBeforeRefuel, speedAfterRefuel);
}

// --- 4. Energy draw + regen + recharge ----------------------------------------

void test_energy_draw_regen() {
    using namespace engine::gameplay;
    auto runtime = create_gameplay_runtime(PhysicsBackend::Jolt);
    add_ground(*runtime, 500.0f);
    engine::vehicles::VehicleAsset asset = make_car_asset();
    // Electric: battery only, tiny capacity so the draw is observable.
    asset.power.energy.capacity = 1.0f;
    asset.power.energy.initialCharge = 1.0f;
    asset.power.energy.drawPerSecond = 0.02f;   // full charge gone in 50 s
    asset.power.energy.regenPerSecond = 0.04f;  // braking regens 2x faster
    asset.power.energy.minChargeToRun = 0.4f;
    auto vehicle = runtime->create_vehicle_from_asset(asset);
    check(vehicle->powered(), "energy: starts powered");

    // Draw by driving until the battery crosses the cut-out (~30 s).
    VehicleInput throttle;
    throttle.throttle = 1.0f;
    const float dt = 1.0f / 60.0f;
    std::size_t ticksToCut = 0;
    for (int i = 0; i < 60 * 40; ++i) {
        vehicle->set_input(throttle);
        vehicle->update(dt);
        runtime->step(dt);
        if (!vehicle->powered() && ticksToCut == 0) ticksToCut = i + 1;
    }
    check(ticksToCut > 0, "energy: motor cuts out after the battery drains");
    check(vehicle->charge_level() < 0.5f, "energy: charge dropped below 0.5");

    // Regen: brake with no throttle recharges past the cut-out.
    VehicleInput brake;
    brake.brake = 1.0f;
    for (int i = 0; i < 60 * 20; ++i) {
        vehicle->set_input(brake);
        vehicle->update(dt);
        runtime->step(dt);
    }
    check(vehicle->charge_level() > 0.4f,
          "energy: regenerative braking recharges past cut-out");
    check(vehicle->powered(), "energy: motor restarts after regen");

    // Recharge() adds a fraction of capacity.
    vehicle->recharge(1.0f);
    check(vehicle->charge_level() == 1.0f, "energy: recharge fills to 1.0");
    std::printf("[vehicle-power] energy: cut at tick %zu, regen recharges to "
                "%.3f, recharge fills OK\n", ticksToCut, vehicle->charge_level());
}

// --- 5. Both systems: fuel AND energy must both be up -------------------------

void test_both_systems() {
    using namespace engine::gameplay;
    auto runtime = create_gameplay_runtime(PhysicsBackend::Jolt);
    add_ground(*runtime);
    engine::vehicles::VehicleAsset asset = make_car_asset();
    asset.power.fuel.capacity = 1.0f;
    asset.power.fuel.initialLevel = 1.0f;
    asset.power.fuel.burnPerSecond = 0.05f;
    asset.power.fuel.minLevelToRun = 0.0f;   // runs to empty
    asset.power.energy.capacity = 1.0f;
    asset.power.energy.initialCharge = 0.2f; // battery nearly dead
    asset.power.energy.drawPerSecond = 0.0f; // no draw; just the charge gate
    asset.power.energy.minChargeToRun = 0.5f;
    auto vehicle = runtime->create_vehicle_from_asset(asset);
    // The battery is already below its cut-out: NOT powered despite full fuel.
    check(!vehicle->powered(), "both: low charge blocks drive despite full fuel");
    vehicle->recharge(0.5f);
    check(vehicle->powered(), "both: recharge unlocks drive");
    std::printf("[vehicle-power] both systems: battery gates fuel OK\n");
}

// --- 6. Beam chassis consumes power the same way ------------------------------

void test_beam_power() {
    using namespace engine::gameplay;
    auto runtime = create_gameplay_runtime(PhysicsBackend::Jolt);
    engine::vehicles::BeamGraphAsset asset;
    asset.name = "power-beam";
    asset.nodes = {
        engine::vehicles::BeamNode{{-1.0f, 0.0f, -1.0f}},
        engine::vehicles::BeamNode{{-1.0f, 0.0f, 1.0f}},
        engine::vehicles::BeamNode{{1.0f, 0.0f, -1.0f}},
        engine::vehicles::BeamNode{{1.0f, 0.0f, 1.0f}},
    };
    asset.beams = {engine::vehicles::Beam{0, 1, 0.9f},
                   engine::vehicles::Beam{2, 3, 0.9f},
                   engine::vehicles::Beam{0, 2, 0.9f},
                   engine::vehicles::Beam{1, 3, 0.9f}};
    engine::vehicles::BeamWheelMount mount;
    mount.node = 0;
    mount.wheel.localPosition = {-0.9f, -0.4f, -0.9f};
    asset.wheels.push_back(mount);
    mount.node = 1;
    mount.wheel.localPosition = {-0.9f, -0.4f, 0.9f};
    asset.wheels.push_back(mount);
    mount.node = 2;
    mount.wheel.localPosition = {0.9f, -0.4f, -0.9f};
    asset.wheels.push_back(mount);
    mount.node = 3;
    mount.wheel.localPosition = {0.9f, -0.4f, 0.9f};
    asset.wheels.push_back(mount);
    asset.power.fuel.capacity = 1.0f;
    asset.power.fuel.initialLevel = 1.0f;
    asset.power.fuel.burnPerSecond = 0.05f;
    asset.power.fuel.minLevelToRun = 0.5f;
    auto beam = runtime->create_beam_vehicle(asset);
    check(beam != nullptr && beam->valid(), "beam vehicle assembled");
    check(beam->powered(), "beam: starts powered");

    VehicleInput throttle;
    throttle.throttle = 1.0f;
    const float dt = 1.0f / 60.0f;
    for (int i = 0; i < 60 * 15; ++i) {
        beam->set_input(throttle);
        beam->update(dt);
    }
    check(!beam->powered(), "beam: engine cuts out after burning fuel");
    check(beam->fuel_level() < 0.6f, "beam: fuel level dropped");
    beam->refuel(1.0f);
    check(beam->powered(), "beam: refuel restores power");
    std::printf("[vehicle-power] beam chassis: fuel burn + cut + refuel OK\n");
}

// --- 7. Determinism ------------------------------------------------------------

void test_determinism() {
    using namespace engine::gameplay;
    engine::vehicles::VehicleAsset asset = make_car_asset();
    asset.power.fuel.capacity = 1.0f;
    asset.power.fuel.initialLevel = 1.0f;
    asset.power.fuel.burnPerSecond = 0.05f;
    asset.power.fuel.minLevelToRun = 0.5f;
    asset.power.controls.throttleSensitivity = 1.7f;

    auto run = [&](float& fuelAfter, float& zAfter) {
        auto runtime = create_gameplay_runtime(PhysicsBackend::Jolt);
        add_ground(*runtime);
        auto vehicle = runtime->create_vehicle_from_asset(asset);
        VehicleInput throttle;
        throttle.throttle = 1.0f;
        const float dt = 1.0f / 60.0f;
        for (int i = 0; i < 60 * 12; ++i) {
            vehicle->set_input(throttle);
            vehicle->update(dt);
            runtime->step(dt);
        }
        fuelAfter = vehicle->fuel_level();
        engine::gameplay::BodyState state;
        runtime->physics().body_state(vehicle->chassis(), state);
        zAfter = state.position.z;
    };

    float fuelA = 0.0f, zA = 0.0f, fuelB = 0.0f, zB = 0.0f;
    run(fuelA, zA);
    run(fuelB, zB);
    check(same_float(fuelA, fuelB), "determinism: fuel levels bit-exact");
    check(same_float(zA, zB), "determinism: chassis positions bit-exact");
    std::printf("[vehicle-power] determinism bit-exact (fuel %.6f, z %.4f) OK\n",
                fuelA, zA);
}

}  // namespace

int main() {
    setvbuf(stdout, nullptr, _IONBF, 0);
    test_json_round_trip();
    test_validation();
    test_control_mapping();
    test_fuel_cuts_drive();
    test_energy_draw_regen();
    test_both_systems();
    test_beam_power();
    test_determinism();
    if (g_failures == 0) {
        std::printf("[vehicle-power] ALL PASSED\n");
        return 0;
    }
    std::printf("[vehicle-power] %d FAILURE(S)\n", g_failures);
    return 1;
}
