#include "AnimationAssets.hpp"
#include <fstream>
#include <iomanip>

namespace Engine {
namespace {
template<class T> void write_vec(std::ostream& o,const T& v){for(glm::length_t i=0;i<v.length();++i)o<<v[i]<<' ';}
template<class T> bool read_vec(std::istream&i,T&v){for(glm::length_t n=0;n<v.length();++n)if(!(i>>v[n]))return false;return true;}
}
bool AnimationAssetIO::save_skeleton(const SkeletonAsset&s,const std::filesystem::path&p){std::ofstream o(p,std::ios::trunc);if(!o)return false;o<<"VulkanEngine.Skeleton 1\n"<<std::quoted(s.id.to_string())<<' '<<std::quoted(s.name)<<' '<<s.bones.size()<<'\n';for(const auto&b:s.bones){o<<std::quoted(b.name)<<' '<<b.parentIndex<<' ';for(int c=0;c<4;++c)write_vec(o,b.localTransform[c]);for(int c=0;c<4;++c)write_vec(o,b.inverseBindMatrix[c]);o<<'\n';}return o.good();}
bool AnimationAssetIO::load_skeleton(SkeletonAsset&s,const std::filesystem::path&p){std::ifstream i(p);std::string m,id,n;unsigned v{};size_t count{};if(!(i>>m>>v)||m!="VulkanEngine.Skeleton"||v!=1||!(i>>std::quoted(id)>>std::quoted(n)>>count)||count>10000)return false;SkeletonAsset loaded;loaded.id=UUID::from_string(id);loaded.name=n;if(!loaded.id.is_valid())return false;loaded.bones.resize(count);for(auto&b:loaded.bones){if(!(i>>std::quoted(b.name)>>b.parentIndex)||b.parentIndex>=static_cast<int>(count))return false;for(int c=0;c<4;++c)if(!read_vec(i,b.localTransform[c]))return false;for(int c=0;c<4;++c)if(!read_vec(i,b.inverseBindMatrix[c]))return false;}s=std::move(loaded);return true;}
bool AnimationAssetIO::save_clip(const AnimationClip&c,const std::filesystem::path&p){std::ofstream o(p,std::ios::trunc);if(!o)return false;o<<"VulkanEngine.AnimationClip 1\n"<<std::quoted(c.id.to_string())<<' '<<std::quoted(c.name)<<' '<<c.duration<<' '<<c.ticksPerSecond<<' '<<c.looping<<' '<<c.rootMotionBone<<' '<<c.tracks.size()<<'\n';for(const auto&t:c.tracks){o<<t.boneIndex<<' '<<t.keyFrames.size()<<'\n';for(const auto&k:t.keyFrames){o<<k.timeStamp<<' ';write_vec(o,k.position);o<<k.rotation.w<<' '<<k.rotation.x<<' '<<k.rotation.y<<' '<<k.rotation.z<<' ';write_vec(o,k.scale);o<<'\n';}}return o.good();}
bool AnimationAssetIO::load_clip(AnimationClip&c,const std::filesystem::path&p){std::ifstream i(p);std::string m,id,n;unsigned v{};size_t tracks{};AnimationClip loaded;if(!(i>>m>>v)||m!="VulkanEngine.AnimationClip"||v!=1||!(i>>std::quoted(id)>>std::quoted(n)>>loaded.duration>>loaded.ticksPerSecond>>loaded.looping>>loaded.rootMotionBone>>tracks)||tracks>100000)return false;loaded.id=UUID::from_string(id);loaded.name=n;if(!loaded.id.is_valid()||loaded.duration<0)return false;loaded.tracks.resize(tracks);for(auto&t:loaded.tracks){size_t keys{};if(!(i>>t.boneIndex>>keys)||keys>1000000)return false;t.keyFrames.resize(keys);float previous=-1;for(auto&k:t.keyFrames){if(!(i>>k.timeStamp)||k.timeStamp<previous||!read_vec(i,k.position)||!(i>>k.rotation.w>>k.rotation.x>>k.rotation.y>>k.rotation.z)||!read_vec(i,k.scale))return false;previous=k.timeStamp;}}c=std::move(loaded);return true;}
void SkinnedMeshRuntime::update(const Pose&pose){if(!skeleton_||pose.local.size()!=skeleton_->bones.size())return;auto globals=AnimationSampler::global_matrices(*skeleton_,pose);skinMatrices_.resize(globals.size());for(size_t i=0;i<globals.size();++i)skinMatrices_[i]=globals[i]*skeleton_->bones[i].inverseBindMatrix;skinned_=source_;for(size_t v=0;v<source_.size();++v){glm::vec4 p(0),n(0);float total=0;for(int j=0;j<4;++j){uint32_t index=source_[v].joints[j];float w=source_[v].weights[j];if(index>=skinMatrices_.size()||w<=0)continue;p+=skinMatrices_[index]*glm::vec4(source_[v].position,1)*w;n+=skinMatrices_[index]*glm::vec4(source_[v].normal,0)*w;total+=w;}if(total>0){skinned_[v].position=glm::vec3(p)/total;skinned_[v].normal=glm::normalize(glm::vec3(n));}}}
} // namespace Engine
