#pragma once
#include "../engine/scene/Scene.hpp"
#include "../engine/scene/Components.hpp"
#include "../engine/assets/GltfGeometry.hpp"
#include "../engine/assets/GltfAssets.hpp"
#include "../engine/assets/RuntimePackage.hpp"
#include "../engine/rendering/vulkan/MaterialPipeline.hpp"
#include "../engine/physics/PhysicsRuntime.hpp"
#include "../engine/physics/Ragdoll.hpp"
#include "../engine/animation/AnimationRuntime.hpp"
#include "../engine/scripting/ScriptRuntime.hpp"
#include "../engine/audio/AudioRuntime.hpp"
#include "../engine/gameplay/WeaponSystem.hpp"
#define GLFW_INCLUDE_VULKAN
#include <GLFW/glfw3.h>
#include <vk_mem_alloc.h>
#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>
#include <iostream>
#include <vector>
#include <unordered_map>
#include <unordered_set>
#include <stdexcept>
#include <chrono>
#include <optional>
#include <set>
#include <cstring>
#include <cstdio>
#include <cstdlib>
#include <fstream>
#include <functional>
#include <algorithm>
using namespace Engine; using namespace Engine::Rendering;
