#version 450

// Mesh vertex shader for material-graph rendering (editor viewport + game).
// Outputs UVs (location 0), world position (location 1) and world normal
// (location 2) for the fragment shader generated by material_graph_to_glsl;
// transforms arrive via the push constant block (mvp + model matrix).

layout (location = 0) in vec3 inPosition;
layout (location = 1) in vec3 inNormal;
layout (location = 2) in vec3 inColor;
layout (location = 3) in vec2 inUv;

layout (push_constant) uniform PushConstants {
    mat4 mvp;    // proj * view * model
    mat4 model;  // world transform
} push;

layout (location = 0) out vec2 vUv;
layout (location = 1) out vec3 vWorldPos;
layout (location = 2) out vec3 vNormal;

void main() {
    vec4 world = push.model * vec4(inPosition, 1.0);
    gl_Position = push.mvp * vec4(inPosition, 1.0);
    vUv = inUv;
    vWorldPos = world.xyz;
    // Note: mat3(model) assumes uniform scale — acceptable for authored meshes.
    vNormal = mat3(push.model) * inNormal;
}
