#include "BuildTools.hpp"
#include <cstdlib>
#include <fstream>
#include <iomanip>
#include <sstream>

namespace Engine::Tools { namespace fs=std::filesystem;
namespace {
std::string quote(const fs::path&p){return '"'+p.string()+'"';}
bool copy_tree(const fs::path&from,const fs::path&to,std::vector<fs::path>&outputs,std::string&error){std::error_code ec;if(!fs::exists(from)){error="Missing input: "+from.string();return false;}for(auto it=fs::recursive_directory_iterator(from,ec);!ec&&it!=fs::recursive_directory_iterator();++it){auto rel=fs::relative(it->path(),from,ec);if(ec)break;auto dest=to/rel;if(it->is_directory())fs::create_directories(dest,ec);else{fs::create_directories(dest.parent_path(),ec);fs::copy_file(it->path(),dest,fs::copy_options::overwrite_existing,ec);if(!ec)outputs.push_back(dest);}if(ec)break;}if(ec){error=ec.message();return false;}return true;}
}
ToolResult ShaderCompiler::compile(const fs::path&source,const fs::path&output,const ShaderCompileOptions&o){ToolResult r;std::error_code ec;if(!fs::is_regular_file(source,ec)){r.message="Shader source does not exist";return r;}if(o.stage.empty()){r.message="Shader stage is required";return r;}fs::create_directories(output.parent_path(),ec);if(ec){r.message=ec.message();return r;}std::ostringstream command;command<<"glslc "<<quote(source)<<" -fshader-stage="<<o.stage<<" -fentry-point="<<o.entry<<" -o "<<quote(output);for(const auto&i:o.includeDirectories)command<<" -I"<<quote(i);for(const auto&d:o.defines)command<<" -D"<<d;if(o.debug)command<<" -g";int code=std::system(command.str().c_str());if(code!=0||!fs::is_regular_file(output,ec)||fs::file_size(output,ec)<4){r.message="glslc failed with code "+std::to_string(code);return r;}r.success=true;r.message="Compiled "+source.string();r.outputs.push_back(output);return r;}
ToolResult ProjectGenerator::generate(const fs::path&directory,const ProjectOptions&o){ToolResult r;if(o.name.empty()){r.message="Project name is required";return r;}std::error_code ec;if(fs::exists(directory,ec)&&!fs::is_empty(directory,ec)){r.message="Destination is not empty";return r;}const fs::path staging=directory.string()+".staging";fs::remove_all(staging,ec);fs::create_directories(staging/"Assets",ec);fs::create_directories(staging/"Source",ec);fs::create_directories(staging/"Config",ec);if(ec){r.message=ec.message();return r;}{std::ofstream p(staging/"project.json");p<<"{\n  \"name\": "<<std::quoted(o.name)<<",\n  \"engine\": "<<std::quoted(o.enginePath.generic_string())<<",\n  \"plugins\": ["<<(o.voxelPlugin?"\"Voxel\"":"")<<"]\n}\n";}{std::ofstream c(staging/"CMakeLists.txt");c<<"cmake_minimum_required(VERSION 3.24)\nproject("<<o.name<<" LANGUAGES CXX)\nset(CMAKE_CXX_STANDARD 20)\nadd_executable("<<o.name<<" Source/main.cpp)\n";}{std::ofstream m(staging/"Source/main.cpp");m<<"#include <iostream>\nint main(){ std::cout << \""<<o.name<<" started\\n\"; return 0; }\n";}{std::ofstream cfg(staging/"Config/Plugins.ini");cfg<<"Voxel="<<(o.voxelPlugin?"true":"false")<<"\n";}if(fs::exists(directory,ec))fs::remove_all(directory,ec);fs::rename(staging,directory,ec);if(ec){r.message=ec.message();fs::remove_all(staging);return r;}r.success=true;r.message="Generated project "+o.name;r.outputs={directory/"project.json",directory/"CMakeLists.txt",directory/"Source/main.cpp"};return r;}
ToolResult PackageBuilder::build(const fs::path&exe,const fs::path&content,const fs::path&output,const PackageOptions&o){ToolResult r;std::error_code ec;if(!fs::is_regular_file(exe,ec)){r.message="Executable is missing";return r;}const fs::path staging=output.string()+".staging";fs::remove_all(staging,ec);fs::create_directories(staging/"Bin",ec);if(ec){r.message=ec.message();return r;}fs::copy_file(exe,staging/"Bin"/exe.filename(),fs::copy_options::overwrite_existing,ec);if(ec){r.message=ec.message();return r;}r.outputs.push_back(staging/"Bin"/exe.filename());if(!copy_tree(content,staging/"Content",r.outputs,r.message)){fs::remove_all(staging);return r;}if(o.includeSymbols){fs::path pdb=exe;pdb.replace_extension(".pdb");if(fs::exists(pdb)){fs::copy_file(pdb,staging/"Bin"/pdb.filename(),fs::copy_options::overwrite_existing,ec);if(!ec)r.outputs.push_back(staging/"Bin"/pdb.filename());}}{std::ofstream manifest(staging/"PackageManifest.txt");manifest<<"VulkanEngine.Package 1\nplatform "<<std::quoted(o.platform)<<"\nconfiguration "<<std::quoted(o.configuration)<<"\nfiles "<<r.outputs.size()<<"\n";for(auto&f:r.outputs)manifest<<std::quoted(fs::relative(f,staging).generic_string())<<'\n';}fs::remove_all(output,ec);fs::rename(staging,output,ec);if(ec){r.message=ec.message();fs::remove_all(staging);return r;}for(auto&f:r.outputs)f=output/fs::relative(f,staging);r.success=true;r.message="Published package at "+output.string();return r;}
} // namespace Engine::Tools
