@echo off
call "C:\Program Files\Microsoft Visual Studio\18\Community\VC\Auxiliary\Build\vcvars64.bat"
cd /d "C:\Users\fahre\.gemini\antigravity\scratch\vulkan_craft\engine"
set SPH=external\solutions\splishsplash
set EIG=%SPH%\extern\eigen
set OUT=tools\portability\_sph_gate
set CFLAGS=/nologo /O2 /std:c++20 /EHsc /DNDEBUG /D_USE_MATH_DEFINES /utf-8 /I%SPH% /I%SPH%\SPlisHSPlasH /I%SPH%\Utilities /I%EIG% /I%SPH%\extern\GenericParameters /I%SPH%\extern\CompactNSearch\include /I%SPH%\extern\Discregrid\include /DUSE_CompactNSearch
cl %CFLAGS% /Fo%OUT%\ /c "%SPH%\extern\tinyexpr\tinyexpr.c"
cl %CFLAGS% /Fo%OUT%\ /c "%SPH%\SPlisHSPlasH\Simulation.cpp"
cl %CFLAGS% /Fo%OUT%\ /c "%SPH%\SPlisHSPlasH\TimeManager.cpp"
cl %CFLAGS% /Fo%OUT%\ /c "%SPH%\SPlisHSPlasH\TimeStep.cpp"
cl %CFLAGS% /Fo%OUT%\ /c "%SPH%\SPlisHSPlasH\FluidModel.cpp"
cl %CFLAGS% /Fo%OUT%\ /c "%SPH%\SPlisHSPlasH\Emitter.cpp"
cl %CFLAGS% /Fo%OUT%\ /c "%SPH%\SPlisHSPlasH\EmitterSystem.cpp"
cl %CFLAGS% /Fo%OUT%\ /c "%SPH%\SPlisHSPlasH\BoundaryModel.cpp"
cl %CFLAGS% /Fo%OUT%\ /c "%SPH%\SPlisHSPlasH\BoundaryModel_Akinci2012.cpp"
cl %CFLAGS% /Fo%OUT%\ /c "%SPH%\SPlisHSPlasH\BoundaryModel_Bender2019.cpp"
cl %CFLAGS% /Fo%OUT%\ /c "%SPH%\SPlisHSPlasH\BoundaryModel_Koschier2017.cpp"
cl %CFLAGS% /Fo%OUT%\ /c "%SPH%\SPlisHSPlasH\SPHKernels.cpp"
cl %CFLAGS% /Fo%OUT%\ /c "%SPH%\SPlisHSPlasH\TriangleMesh.cpp"
cl %CFLAGS% /Fo%OUT%\ /c "%SPH%\SPlisHSPlasH\NonPressureForceBase.cpp"
cl %CFLAGS% /Fo%OUT%\ /c "%SPH%\SPlisHSPlasH\NonPressureForceRegistration.cpp"
cl %CFLAGS% /Fo%OUT%\ /c "%SPH%\SPlisHSPlasH\XSPH.cpp"
cl %CFLAGS% /Fo%OUT%\ /c "%SPH%\SPlisHSPlasH\AnimationField.cpp"
cl %CFLAGS% /Fo%OUT%\ /c "%SPH%\SPlisHSPlasH\AnimationFieldSystem.cpp"
cl %CFLAGS% /Fo%OUT%\ /c "%SPH%\SPlisHSPlasH\Utilities\CholeskyAVXSolver.cpp"
cl %CFLAGS% /Fo%OUT%\ /c "%SPH%\SPlisHSPlasH\Utilities\DebugTools.cpp"
cl %CFLAGS% /Fo%OUT%\ /c "%SPH%\SPlisHSPlasH\Utilities\GaussQuadrature.cpp"
cl %CFLAGS% /Fo%OUT%\ /c "%SPH%\SPlisHSPlasH\Utilities\MathFunctions.cpp"
cl %CFLAGS% /Fo%OUT%\ /c "%SPH%\SPlisHSPlasH\Utilities\MeshImport.cpp"
cl %CFLAGS% /Fo%OUT%\ /c "%SPH%\SPlisHSPlasH\Utilities\PoissonDiskSampling.cpp"
cl %CFLAGS% /Fo%OUT%\ /c "%SPH%\SPlisHSPlasH\Utilities\RegularSampling2D.cpp"
cl %CFLAGS% /Fo%OUT%\ /c "%SPH%\SPlisHSPlasH\Utilities\RegularTriangleSampling.cpp"
cl %CFLAGS% /Fo%OUT%\ /c "%SPH%\SPlisHSPlasH\Utilities\SDFFunctions.cpp"
cl %CFLAGS% /Fo%OUT%\ /c "%SPH%\SPlisHSPlasH\Utilities\SceneLoader.cpp"
cl %CFLAGS% /Fo%OUT%\ /c "%SPH%\SPlisHSPlasH\Utilities\SceneParameterObjects.cpp"
cl %CFLAGS% /Fo%OUT%\ /c "%SPH%\SPlisHSPlasH\Utilities\SceneWriter.cpp"
cl %CFLAGS% /Fo%OUT%\ /c "%SPH%\SPlisHSPlasH\Utilities\SimpleQuadrature.cpp"
cl %CFLAGS% /Fo%OUT%\ /c "%SPH%\SPlisHSPlasH\Utilities\VolumeSampling.cpp"
cl %CFLAGS% /Fo%OUT%\ /c "%SPH%\SPlisHSPlasH\Utilities\WindingNumbers.cpp"
cl %CFLAGS% /Fo%OUT%\ /c "%SPH%\SPlisHSPlasH\WCSPH\SimulationDataWCSPH.cpp"
cl %CFLAGS% /Fo%OUT%\ /c "%SPH%\SPlisHSPlasH\WCSPH\TimeStepWCSPH.cpp"
cl %CFLAGS% /Fo%OUT%\ /c "%SPH%\SPlisHSPlasH\PCISPH\SimulationDataPCISPH.cpp"
cl %CFLAGS% /Fo%OUT%\ /c "%SPH%\SPlisHSPlasH\PCISPH\TimeStepPCISPH.cpp"
cl %CFLAGS% /Fo%OUT%\ /c "%SPH%\SPlisHSPlasH\PBF\SimulationDataPBF.cpp"
cl %CFLAGS% /Fo%OUT%\ /c "%SPH%\SPlisHSPlasH\PBF\TimeIntegration.cpp"
cl %CFLAGS% /Fo%OUT%\ /c "%SPH%\SPlisHSPlasH\PBF\TimeStepPBF.cpp"
cl %CFLAGS% /Fo%OUT%\ /c "%SPH%\SPlisHSPlasH\DFSPH\SimulationDataDFSPH.cpp"
cl %CFLAGS% /Fo%OUT%\ /c "%SPH%\SPlisHSPlasH\DFSPH\TimeStepDFSPH.cpp"
cl %CFLAGS% /Fo%OUT%\ /c "%SPH%\SPlisHSPlasH\IISPH\SimulationDataIISPH.cpp"
cl %CFLAGS% /Fo%OUT%\ /c "%SPH%\SPlisHSPlasH\IISPH\TimeStepIISPH.cpp"
cl %CFLAGS% /Fo%OUT%\ /c "%SPH%\SPlisHSPlasH\PF\SimulationDataPF.cpp"
cl %CFLAGS% /Fo%OUT%\ /c "%SPH%\SPlisHSPlasH\PF\TimeStepPF.cpp"
cl %CFLAGS% /Fo%OUT%\ /c "%SPH%\SPlisHSPlasH\ICSPH\SimulationDataICSPH.cpp"
cl %CFLAGS% /Fo%OUT%\ /c "%SPH%\SPlisHSPlasH\ICSPH\TimeStepICSPH.cpp"
cl %CFLAGS% /Fo%OUT%\ /c "%SPH%\Utilities\PartioReaderWriter.cpp"
echo === COMPILE DONE ===
